spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: naveen
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

app:
  shortUrlLength: 9
server:
  port: 8001
# This value must come from environment variable
#jwt:
#  secret:
